/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.metas.camel.externalsystems.amazon.api.model.orders;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.metas.camel.externalsystems.amazon.api.model.orders.TaxClassification;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MarketplaceTaxInfo
 */
public class MarketplaceTaxInfoTest {
    private final MarketplaceTaxInfo model = new MarketplaceTaxInfo();

    /**
     * Model tests for MarketplaceTaxInfo
     */
    @Test
    public void testMarketplaceTaxInfo() {
        // TODO: test MarketplaceTaxInfo
    }

    /**
     * Test the property 'taxClassifications'
     */
    @Test
    public void taxClassificationsTest() {
        // TODO: test taxClassifications
    }

}
