/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.metas.camel.externalsystems.amazon.api.model.orders;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.metas.camel.externalsystems.amazon.api.model.orders.BuyerCustomizedInfoDetail;
import de.metas.camel.externalsystems.amazon.api.model.orders.Money;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OrderItemBuyerInfo
 */
public class OrderItemBuyerInfoTest {
    private final OrderItemBuyerInfo model = new OrderItemBuyerInfo();

    /**
     * Model tests for OrderItemBuyerInfo
     */
    @Test
    public void testOrderItemBuyerInfo() {
        // TODO: test OrderItemBuyerInfo
    }

    /**
     * Test the property 'orderItemId'
     */
    @Test
    public void orderItemIdTest() {
        // TODO: test orderItemId
    }

    /**
     * Test the property 'buyerCustomizedInfo'
     */
    @Test
    public void buyerCustomizedInfoTest() {
        // TODO: test buyerCustomizedInfo
    }

    /**
     * Test the property 'giftWrapPrice'
     */
    @Test
    public void giftWrapPriceTest() {
        // TODO: test giftWrapPrice
    }

    /**
     * Test the property 'giftWrapTax'
     */
    @Test
    public void giftWrapTaxTest() {
        // TODO: test giftWrapTax
    }

    /**
     * Test the property 'giftMessageText'
     */
    @Test
    public void giftMessageTextTest() {
        // TODO: test giftMessageText
    }

    /**
     * Test the property 'giftWrapLevel'
     */
    @Test
    public void giftWrapLevelTest() {
        // TODO: test giftWrapLevel
    }

}
