/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.metas.camel.externalsystems.amazon.api.model.orders;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.metas.camel.externalsystems.amazon.api.model.orders.Money;
import de.metas.camel.externalsystems.amazon.api.model.orders.PointsGrantedDetail;
import de.metas.camel.externalsystems.amazon.api.model.orders.ProductInfoDetail;
import de.metas.camel.externalsystems.amazon.api.model.orders.TaxCollection;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OrderItem
 */
public class OrderItemTest {
    private final OrderItem model = new OrderItem();

    /**
     * Model tests for OrderItem
     */
    @Test
    public void testOrderItem() {
        // TODO: test OrderItem
    }

    /**
     * Test the property 'ASIN'
     */
    @Test
    public void ASINTest() {
        // TODO: test ASIN
    }

    /**
     * Test the property 'sellerSKU'
     */
    @Test
    public void sellerSKUTest() {
        // TODO: test sellerSKU
    }

    /**
     * Test the property 'orderItemId'
     */
    @Test
    public void orderItemIdTest() {
        // TODO: test orderItemId
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'quantityOrdered'
     */
    @Test
    public void quantityOrderedTest() {
        // TODO: test quantityOrdered
    }

    /**
     * Test the property 'quantityShipped'
     */
    @Test
    public void quantityShippedTest() {
        // TODO: test quantityShipped
    }

    /**
     * Test the property 'productInfo'
     */
    @Test
    public void productInfoTest() {
        // TODO: test productInfo
    }

    /**
     * Test the property 'pointsGranted'
     */
    @Test
    public void pointsGrantedTest() {
        // TODO: test pointsGranted
    }

    /**
     * Test the property 'itemPrice'
     */
    @Test
    public void itemPriceTest() {
        // TODO: test itemPrice
    }

    /**
     * Test the property 'shippingPrice'
     */
    @Test
    public void shippingPriceTest() {
        // TODO: test shippingPrice
    }

    /**
     * Test the property 'itemTax'
     */
    @Test
    public void itemTaxTest() {
        // TODO: test itemTax
    }

    /**
     * Test the property 'shippingTax'
     */
    @Test
    public void shippingTaxTest() {
        // TODO: test shippingTax
    }

    /**
     * Test the property 'shippingDiscount'
     */
    @Test
    public void shippingDiscountTest() {
        // TODO: test shippingDiscount
    }

    /**
     * Test the property 'shippingDiscountTax'
     */
    @Test
    public void shippingDiscountTaxTest() {
        // TODO: test shippingDiscountTax
    }

    /**
     * Test the property 'promotionDiscount'
     */
    @Test
    public void promotionDiscountTest() {
        // TODO: test promotionDiscount
    }

    /**
     * Test the property 'promotionDiscountTax'
     */
    @Test
    public void promotionDiscountTaxTest() {
        // TODO: test promotionDiscountTax
    }

    /**
     * Test the property 'promotionIds'
     */
    @Test
    public void promotionIdsTest() {
        // TODO: test promotionIds
    }

    /**
     * Test the property 'coDFee'
     */
    @Test
    public void coDFeeTest() {
        // TODO: test coDFee
    }

    /**
     * Test the property 'coDFeeDiscount'
     */
    @Test
    public void coDFeeDiscountTest() {
        // TODO: test coDFeeDiscount
    }

    /**
     * Test the property 'isGift'
     */
    @Test
    public void isGiftTest() {
        // TODO: test isGift
    }

    /**
     * Test the property 'conditionNote'
     */
    @Test
    public void conditionNoteTest() {
        // TODO: test conditionNote
    }

    /**
     * Test the property 'conditionId'
     */
    @Test
    public void conditionIdTest() {
        // TODO: test conditionId
    }

    /**
     * Test the property 'conditionSubtypeId'
     */
    @Test
    public void conditionSubtypeIdTest() {
        // TODO: test conditionSubtypeId
    }

    /**
     * Test the property 'scheduledDeliveryStartDate'
     */
    @Test
    public void scheduledDeliveryStartDateTest() {
        // TODO: test scheduledDeliveryStartDate
    }

    /**
     * Test the property 'scheduledDeliveryEndDate'
     */
    @Test
    public void scheduledDeliveryEndDateTest() {
        // TODO: test scheduledDeliveryEndDate
    }

    /**
     * Test the property 'priceDesignation'
     */
    @Test
    public void priceDesignationTest() {
        // TODO: test priceDesignation
    }

    /**
     * Test the property 'taxCollection'
     */
    @Test
    public void taxCollectionTest() {
        // TODO: test taxCollection
    }

    /**
     * Test the property 'serialNumberRequired'
     */
    @Test
    public void serialNumberRequiredTest() {
        // TODO: test serialNumberRequired
    }

    /**
     * Test the property 'isTransparency'
     */
    @Test
    public void isTransparencyTest() {
        // TODO: test isTransparency
    }

    /**
     * Test the property 'iossNumber'
     */
    @Test
    public void iossNumberTest() {
        // TODO: test iossNumber
    }

    /**
     * Test the property 'storeChainStoreId'
     */
    @Test
    public void storeChainStoreIdTest() {
        // TODO: test storeChainStoreId
    }

    /**
     * Test the property 'deemedResellerCategory'
     */
    @Test
    public void deemedResellerCategoryTest() {
        // TODO: test deemedResellerCategory
    }

}
