/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.metas.camel.externalsystems.amazon.api.model.orders;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.metas.camel.externalsystems.amazon.api.model.orders.BuyerTaxInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OrderBuyerInfo
 */
public class OrderBuyerInfoTest {
    private final OrderBuyerInfo model = new OrderBuyerInfo();

    /**
     * Model tests for OrderBuyerInfo
     */
    @Test
    public void testOrderBuyerInfo() {
        // TODO: test OrderBuyerInfo
    }

    /**
     * Test the property 'amazonOrderId'
     */
    @Test
    public void amazonOrderIdTest() {
        // TODO: test amazonOrderId
    }

    /**
     * Test the property 'buyerEmail'
     */
    @Test
    public void buyerEmailTest() {
        // TODO: test buyerEmail
    }

    /**
     * Test the property 'buyerName'
     */
    @Test
    public void buyerNameTest() {
        // TODO: test buyerName
    }

    /**
     * Test the property 'buyerCounty'
     */
    @Test
    public void buyerCountyTest() {
        // TODO: test buyerCounty
    }

    /**
     * Test the property 'buyerTaxInfo'
     */
    @Test
    public void buyerTaxInfoTest() {
        // TODO: test buyerTaxInfo
    }

    /**
     * Test the property 'purchaseOrderNumber'
     */
    @Test
    public void purchaseOrderNumberTest() {
        // TODO: test purchaseOrderNumber
    }

}
