/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.metas.camel.externalsystems.amazon.api.model.orders;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.metas.camel.externalsystems.amazon.api.model.orders.Address;
import de.metas.camel.externalsystems.amazon.api.model.orders.FulfillmentInstruction;
import de.metas.camel.externalsystems.amazon.api.model.orders.MarketplaceTaxInfo;
import de.metas.camel.externalsystems.amazon.api.model.orders.Money;
import de.metas.camel.externalsystems.amazon.api.model.orders.PaymentExecutionDetailItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Order
 */
public class OrderTest {
    private final Order model = new Order();

    /**
     * Model tests for Order
     */
    @Test
    public void testOrder() {
        // TODO: test Order
    }

    /**
     * Test the property 'amazonOrderId'
     */
    @Test
    public void amazonOrderIdTest() {
        // TODO: test amazonOrderId
    }

    /**
     * Test the property 'sellerOrderId'
     */
    @Test
    public void sellerOrderIdTest() {
        // TODO: test sellerOrderId
    }

    /**
     * Test the property 'purchaseDate'
     */
    @Test
    public void purchaseDateTest() {
        // TODO: test purchaseDate
    }

    /**
     * Test the property 'lastUpdateDate'
     */
    @Test
    public void lastUpdateDateTest() {
        // TODO: test lastUpdateDate
    }

    /**
     * Test the property 'orderStatus'
     */
    @Test
    public void orderStatusTest() {
        // TODO: test orderStatus
    }

    /**
     * Test the property 'fulfillmentChannel'
     */
    @Test
    public void fulfillmentChannelTest() {
        // TODO: test fulfillmentChannel
    }

    /**
     * Test the property 'salesChannel'
     */
    @Test
    public void salesChannelTest() {
        // TODO: test salesChannel
    }

    /**
     * Test the property 'orderChannel'
     */
    @Test
    public void orderChannelTest() {
        // TODO: test orderChannel
    }

    /**
     * Test the property 'shipServiceLevel'
     */
    @Test
    public void shipServiceLevelTest() {
        // TODO: test shipServiceLevel
    }

    /**
     * Test the property 'orderTotal'
     */
    @Test
    public void orderTotalTest() {
        // TODO: test orderTotal
    }

    /**
     * Test the property 'numberOfItemsShipped'
     */
    @Test
    public void numberOfItemsShippedTest() {
        // TODO: test numberOfItemsShipped
    }

    /**
     * Test the property 'numberOfItemsUnshipped'
     */
    @Test
    public void numberOfItemsUnshippedTest() {
        // TODO: test numberOfItemsUnshipped
    }

    /**
     * Test the property 'paymentExecutionDetail'
     */
    @Test
    public void paymentExecutionDetailTest() {
        // TODO: test paymentExecutionDetail
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    public void paymentMethodTest() {
        // TODO: test paymentMethod
    }

    /**
     * Test the property 'paymentMethodDetails'
     */
    @Test
    public void paymentMethodDetailsTest() {
        // TODO: test paymentMethodDetails
    }

    /**
     * Test the property 'marketplaceId'
     */
    @Test
    public void marketplaceIdTest() {
        // TODO: test marketplaceId
    }

    /**
     * Test the property 'shipmentServiceLevelCategory'
     */
    @Test
    public void shipmentServiceLevelCategoryTest() {
        // TODO: test shipmentServiceLevelCategory
    }

    /**
     * Test the property 'easyShipShipmentStatus'
     */
    @Test
    public void easyShipShipmentStatusTest() {
        // TODO: test easyShipShipmentStatus
    }

    /**
     * Test the property 'cbaDisplayableShippingLabel'
     */
    @Test
    public void cbaDisplayableShippingLabelTest() {
        // TODO: test cbaDisplayableShippingLabel
    }

    /**
     * Test the property 'orderType'
     */
    @Test
    public void orderTypeTest() {
        // TODO: test orderType
    }

    /**
     * Test the property 'earliestShipDate'
     */
    @Test
    public void earliestShipDateTest() {
        // TODO: test earliestShipDate
    }

    /**
     * Test the property 'latestShipDate'
     */
    @Test
    public void latestShipDateTest() {
        // TODO: test latestShipDate
    }

    /**
     * Test the property 'earliestDeliveryDate'
     */
    @Test
    public void earliestDeliveryDateTest() {
        // TODO: test earliestDeliveryDate
    }

    /**
     * Test the property 'latestDeliveryDate'
     */
    @Test
    public void latestDeliveryDateTest() {
        // TODO: test latestDeliveryDate
    }

    /**
     * Test the property 'isBusinessOrder'
     */
    @Test
    public void isBusinessOrderTest() {
        // TODO: test isBusinessOrder
    }

    /**
     * Test the property 'isPrime'
     */
    @Test
    public void isPrimeTest() {
        // TODO: test isPrime
    }

    /**
     * Test the property 'isPremiumOrder'
     */
    @Test
    public void isPremiumOrderTest() {
        // TODO: test isPremiumOrder
    }

    /**
     * Test the property 'isGlobalExpressEnabled'
     */
    @Test
    public void isGlobalExpressEnabledTest() {
        // TODO: test isGlobalExpressEnabled
    }

    /**
     * Test the property 'replacedOrderId'
     */
    @Test
    public void replacedOrderIdTest() {
        // TODO: test replacedOrderId
    }

    /**
     * Test the property 'isReplacementOrder'
     */
    @Test
    public void isReplacementOrderTest() {
        // TODO: test isReplacementOrder
    }

    /**
     * Test the property 'promiseResponseDueDate'
     */
    @Test
    public void promiseResponseDueDateTest() {
        // TODO: test promiseResponseDueDate
    }

    /**
     * Test the property 'isEstimatedShipDateSet'
     */
    @Test
    public void isEstimatedShipDateSetTest() {
        // TODO: test isEstimatedShipDateSet
    }

    /**
     * Test the property 'isSoldByAB'
     */
    @Test
    public void isSoldByABTest() {
        // TODO: test isSoldByAB
    }

    /**
     * Test the property 'defaultShipFromLocationAddress'
     */
    @Test
    public void defaultShipFromLocationAddressTest() {
        // TODO: test defaultShipFromLocationAddress
    }

    /**
     * Test the property 'fulfillmentInstruction'
     */
    @Test
    public void fulfillmentInstructionTest() {
        // TODO: test fulfillmentInstruction
    }

    /**
     * Test the property 'isISPU'
     */
    @Test
    public void isISPUTest() {
        // TODO: test isISPU
    }

    /**
     * Test the property 'marketplaceTaxInfo'
     */
    @Test
    public void marketplaceTaxInfoTest() {
        // TODO: test marketplaceTaxInfo
    }

    /**
     * Test the property 'sellerDisplayName'
     */
    @Test
    public void sellerDisplayNameTest() {
        // TODO: test sellerDisplayName
    }

}
