/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.metas.camel.externalsystems.amazon.api.model.orders;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.metas.camel.externalsystems.amazon.api.model.orders.TaxClassification;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Tax information about the buyer.
 */
@ApiModel(description = "Tax information about the buyer.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-19T18:02:29.893848+02:00[Europe/Berlin]")
public class BuyerTaxInfo {
  public static final String SERIALIZED_NAME_COMPANY_LEGAL_NAME = "CompanyLegalName";
  @SerializedName(SERIALIZED_NAME_COMPANY_LEGAL_NAME)
  private String companyLegalName;

  public static final String SERIALIZED_NAME_TAXING_REGION = "TaxingRegion";
  @SerializedName(SERIALIZED_NAME_TAXING_REGION)
  private String taxingRegion;

  public static final String SERIALIZED_NAME_TAX_CLASSIFICATIONS = "TaxClassifications";
  @SerializedName(SERIALIZED_NAME_TAX_CLASSIFICATIONS)
  private List<TaxClassification> taxClassifications = null;


  public BuyerTaxInfo companyLegalName(String companyLegalName) {
    
    this.companyLegalName = companyLegalName;
    return this;
  }

   /**
   * The legal name of the company.
   * @return companyLegalName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The legal name of the company.")

  public String getCompanyLegalName() {
    return companyLegalName;
  }


  public void setCompanyLegalName(String companyLegalName) {
    this.companyLegalName = companyLegalName;
  }


  public BuyerTaxInfo taxingRegion(String taxingRegion) {
    
    this.taxingRegion = taxingRegion;
    return this;
  }

   /**
   * The country or region imposing the tax.
   * @return taxingRegion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The country or region imposing the tax.")

  public String getTaxingRegion() {
    return taxingRegion;
  }


  public void setTaxingRegion(String taxingRegion) {
    this.taxingRegion = taxingRegion;
  }


  public BuyerTaxInfo taxClassifications(List<TaxClassification> taxClassifications) {
    
    this.taxClassifications = taxClassifications;
    return this;
  }

  public BuyerTaxInfo addTaxClassificationsItem(TaxClassification taxClassificationsItem) {
    if (this.taxClassifications == null) {
      this.taxClassifications = new ArrayList<>();
    }
    this.taxClassifications.add(taxClassificationsItem);
    return this;
  }

   /**
   * A list of tax classifications that apply to the order.
   * @return taxClassifications
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of tax classifications that apply to the order.")

  public List<TaxClassification> getTaxClassifications() {
    return taxClassifications;
  }


  public void setTaxClassifications(List<TaxClassification> taxClassifications) {
    this.taxClassifications = taxClassifications;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuyerTaxInfo buyerTaxInfo = (BuyerTaxInfo) o;
    return Objects.equals(this.companyLegalName, buyerTaxInfo.companyLegalName) &&
        Objects.equals(this.taxingRegion, buyerTaxInfo.taxingRegion) &&
        Objects.equals(this.taxClassifications, buyerTaxInfo.taxClassifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyLegalName, taxingRegion, taxClassifications);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuyerTaxInfo {\n");
    sb.append("    companyLegalName: ").append(toIndentedString(companyLegalName)).append("\n");
    sb.append("    taxingRegion: ").append(toIndentedString(taxingRegion)).append("\n");
    sb.append("    taxClassifications: ").append(toIndentedString(taxClassifications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

