/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.metas.camel.externalsystems.amazon.api.model.orders;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Buyer information for custom orders from the Amazon Custom program.
 */
@ApiModel(description = "Buyer information for custom orders from the Amazon Custom program.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-19T18:02:29.893848+02:00[Europe/Berlin]")
public class BuyerCustomizedInfoDetail {
  public static final String SERIALIZED_NAME_CUSTOMIZED_U_R_L = "CustomizedURL";
  @SerializedName(SERIALIZED_NAME_CUSTOMIZED_U_R_L)
  private String customizedURL;


  public BuyerCustomizedInfoDetail customizedURL(String customizedURL) {
    
    this.customizedURL = customizedURL;
    return this;
  }

   /**
   * The location of a zip file containing Amazon Custom data.
   * @return customizedURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The location of a zip file containing Amazon Custom data.")

  public String getCustomizedURL() {
    return customizedURL;
  }


  public void setCustomizedURL(String customizedURL) {
    this.customizedURL = customizedURL;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuyerCustomizedInfoDetail buyerCustomizedInfoDetail = (BuyerCustomizedInfoDetail) o;
    return Objects.equals(this.customizedURL, buyerCustomizedInfoDetail.customizedURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customizedURL);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuyerCustomizedInfoDetail {\n");
    sb.append("    customizedURL: ").append(toIndentedString(customizedURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

