/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.metas.camel.externalsystems.amazon.api.model.orders;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Contains the instructions about the fulfillment like where should it be fulfilled from.
 */
@ApiModel(description = "Contains the instructions about the fulfillment like where should it be fulfilled from.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-19T18:02:29.893848+02:00[Europe/Berlin]")
public class FulfillmentInstruction {
  public static final String SERIALIZED_NAME_FULFILLMENT_SUPPLY_SOURCE_ID = "FulfillmentSupplySourceId";
  @SerializedName(SERIALIZED_NAME_FULFILLMENT_SUPPLY_SOURCE_ID)
  private String fulfillmentSupplySourceId;


  public FulfillmentInstruction fulfillmentSupplySourceId(String fulfillmentSupplySourceId) {
    
    this.fulfillmentSupplySourceId = fulfillmentSupplySourceId;
    return this;
  }

   /**
   * Denotes the recommended sourceId where the order should be fulfilled from.
   * @return fulfillmentSupplySourceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Denotes the recommended sourceId where the order should be fulfilled from.")

  public String getFulfillmentSupplySourceId() {
    return fulfillmentSupplySourceId;
  }


  public void setFulfillmentSupplySourceId(String fulfillmentSupplySourceId) {
    this.fulfillmentSupplySourceId = fulfillmentSupplySourceId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FulfillmentInstruction fulfillmentInstruction = (FulfillmentInstruction) o;
    return Objects.equals(this.fulfillmentSupplySourceId, fulfillmentInstruction.fulfillmentSupplySourceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fulfillmentSupplySourceId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FulfillmentInstruction {\n");
    sb.append("    fulfillmentSupplySourceId: ").append(toIndentedString(fulfillmentSupplySourceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

