/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.metas.camel.externalsystems.amazon.api.model.orders;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.metas.camel.externalsystems.amazon.api.model.orders.OrderItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * The order items list along with the order ID.
 */
@ApiModel(description = "The order items list along with the order ID.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-19T18:02:29.893848+02:00[Europe/Berlin]")
public class OrderItemsList {
  public static final String SERIALIZED_NAME_ORDER_ITEMS = "OrderItems";
  @SerializedName(SERIALIZED_NAME_ORDER_ITEMS)
  private List<OrderItem> orderItems = new ArrayList<>();

  public static final String SERIALIZED_NAME_NEXT_TOKEN = "NextToken";
  @SerializedName(SERIALIZED_NAME_NEXT_TOKEN)
  private String nextToken;

  public static final String SERIALIZED_NAME_AMAZON_ORDER_ID = "AmazonOrderId";
  @SerializedName(SERIALIZED_NAME_AMAZON_ORDER_ID)
  private String amazonOrderId;


  public OrderItemsList orderItems(List<OrderItem> orderItems) {
    
    this.orderItems = orderItems;
    return this;
  }

  public OrderItemsList addOrderItemsItem(OrderItem orderItemsItem) {
    this.orderItems.add(orderItemsItem);
    return this;
  }

   /**
   * A list of order items.
   * @return orderItems
  **/
  @ApiModelProperty(required = true, value = "A list of order items.")

  public List<OrderItem> getOrderItems() {
    return orderItems;
  }


  public void setOrderItems(List<OrderItem> orderItems) {
    this.orderItems = orderItems;
  }


  public OrderItemsList nextToken(String nextToken) {
    
    this.nextToken = nextToken;
    return this;
  }

   /**
   * When present and not empty, pass this string token in the next request to return the next response page.
   * @return nextToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When present and not empty, pass this string token in the next request to return the next response page.")

  public String getNextToken() {
    return nextToken;
  }


  public void setNextToken(String nextToken) {
    this.nextToken = nextToken;
  }


  public OrderItemsList amazonOrderId(String amazonOrderId) {
    
    this.amazonOrderId = amazonOrderId;
    return this;
  }

   /**
   * An Amazon-defined order identifier, in 3-7-7 format.
   * @return amazonOrderId
  **/
  @ApiModelProperty(required = true, value = "An Amazon-defined order identifier, in 3-7-7 format.")

  public String getAmazonOrderId() {
    return amazonOrderId;
  }


  public void setAmazonOrderId(String amazonOrderId) {
    this.amazonOrderId = amazonOrderId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderItemsList orderItemsList = (OrderItemsList) o;
    return Objects.equals(this.orderItems, orderItemsList.orderItems) &&
        Objects.equals(this.nextToken, orderItemsList.nextToken) &&
        Objects.equals(this.amazonOrderId, orderItemsList.amazonOrderId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderItems, nextToken, amazonOrderId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderItemsList {\n");
    sb.append("    orderItems: ").append(toIndentedString(orderItems)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("    amazonOrderId: ").append(toIndentedString(amazonOrderId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

