/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.metas.camel.externalsystems.amazon.api.model.orders;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.metas.camel.externalsystems.amazon.api.model.orders.Address;
import de.metas.camel.externalsystems.amazon.api.model.orders.FulfillmentInstruction;
import de.metas.camel.externalsystems.amazon.api.model.orders.MarketplaceTaxInfo;
import de.metas.camel.externalsystems.amazon.api.model.orders.Money;
import de.metas.camel.externalsystems.amazon.api.model.orders.PaymentExecutionDetailItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Order information.
 */
@ApiModel(description = "Order information.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-19T18:02:29.893848+02:00[Europe/Berlin]")
public class Order {
  public static final String SERIALIZED_NAME_AMAZON_ORDER_ID = "AmazonOrderId";
  @SerializedName(SERIALIZED_NAME_AMAZON_ORDER_ID)
  private String amazonOrderId;

  public static final String SERIALIZED_NAME_SELLER_ORDER_ID = "SellerOrderId";
  @SerializedName(SERIALIZED_NAME_SELLER_ORDER_ID)
  private String sellerOrderId;

  public static final String SERIALIZED_NAME_PURCHASE_DATE = "PurchaseDate";
  @SerializedName(SERIALIZED_NAME_PURCHASE_DATE)
  private String purchaseDate;

  public static final String SERIALIZED_NAME_LAST_UPDATE_DATE = "LastUpdateDate";
  @SerializedName(SERIALIZED_NAME_LAST_UPDATE_DATE)
  private String lastUpdateDate;

  /**
   * The current order status.
   */
  @JsonAdapter(OrderStatusEnum.Adapter.class)
  public enum OrderStatusEnum {
    PENDING("Pending"),
    
    UNSHIPPED("Unshipped"),
    
    PARTIALLYSHIPPED("PartiallyShipped"),
    
    SHIPPED("Shipped"),
    
    CANCELED("Canceled"),
    
    UNFULFILLABLE("Unfulfillable"),
    
    INVOICEUNCONFIRMED("InvoiceUnconfirmed"),
    
    PENDINGAVAILABILITY("PendingAvailability");

    private String value;

    OrderStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OrderStatusEnum fromValue(String value) {
      for (OrderStatusEnum b : OrderStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<OrderStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OrderStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OrderStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return OrderStatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ORDER_STATUS = "OrderStatus";
  @SerializedName(SERIALIZED_NAME_ORDER_STATUS)
  private OrderStatusEnum orderStatus;

  /**
   * Whether the order was fulfilled by Amazon (AFN) or by the seller (MFN).
   */
  @JsonAdapter(FulfillmentChannelEnum.Adapter.class)
  public enum FulfillmentChannelEnum {
    MFN("MFN"),
    
    AFN("AFN");

    private String value;

    FulfillmentChannelEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FulfillmentChannelEnum fromValue(String value) {
      for (FulfillmentChannelEnum b : FulfillmentChannelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<FulfillmentChannelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FulfillmentChannelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FulfillmentChannelEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return FulfillmentChannelEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_FULFILLMENT_CHANNEL = "FulfillmentChannel";
  @SerializedName(SERIALIZED_NAME_FULFILLMENT_CHANNEL)
  private FulfillmentChannelEnum fulfillmentChannel;

  public static final String SERIALIZED_NAME_SALES_CHANNEL = "SalesChannel";
  @SerializedName(SERIALIZED_NAME_SALES_CHANNEL)
  private String salesChannel;

  public static final String SERIALIZED_NAME_ORDER_CHANNEL = "OrderChannel";
  @SerializedName(SERIALIZED_NAME_ORDER_CHANNEL)
  private String orderChannel;

  public static final String SERIALIZED_NAME_SHIP_SERVICE_LEVEL = "ShipServiceLevel";
  @SerializedName(SERIALIZED_NAME_SHIP_SERVICE_LEVEL)
  private String shipServiceLevel;

  public static final String SERIALIZED_NAME_ORDER_TOTAL = "OrderTotal";
  @SerializedName(SERIALIZED_NAME_ORDER_TOTAL)
  private Money orderTotal;

  public static final String SERIALIZED_NAME_NUMBER_OF_ITEMS_SHIPPED = "NumberOfItemsShipped";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_ITEMS_SHIPPED)
  private Integer numberOfItemsShipped;

  public static final String SERIALIZED_NAME_NUMBER_OF_ITEMS_UNSHIPPED = "NumberOfItemsUnshipped";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_ITEMS_UNSHIPPED)
  private Integer numberOfItemsUnshipped;

  public static final String SERIALIZED_NAME_PAYMENT_EXECUTION_DETAIL = "PaymentExecutionDetail";
  @SerializedName(SERIALIZED_NAME_PAYMENT_EXECUTION_DETAIL)
  private List<PaymentExecutionDetailItem> paymentExecutionDetail = null;

  /**
   * The payment method for the order. This property is limited to Cash On Delivery (COD) and Convenience Store (CVS) payment methods. Unless you need the specific COD payment information provided by the PaymentExecutionDetailItem object, we recommend using the PaymentMethodDetails property to get payment method information.
   */
  @JsonAdapter(PaymentMethodEnum.Adapter.class)
  public enum PaymentMethodEnum {
    COD("COD"),
    
    CVS("CVS"),
    
    OTHER("Other");

    private String value;

    PaymentMethodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PaymentMethodEnum fromValue(String value) {
      for (PaymentMethodEnum b : PaymentMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PaymentMethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PaymentMethodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PaymentMethodEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PaymentMethodEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_PAYMENT_METHOD = "PaymentMethod";
  @SerializedName(SERIALIZED_NAME_PAYMENT_METHOD)
  private PaymentMethodEnum paymentMethod;

  public static final String SERIALIZED_NAME_PAYMENT_METHOD_DETAILS = "PaymentMethodDetails";
  @SerializedName(SERIALIZED_NAME_PAYMENT_METHOD_DETAILS)
  private List<String> paymentMethodDetails = null;

  public static final String SERIALIZED_NAME_MARKETPLACE_ID = "MarketplaceId";
  @SerializedName(SERIALIZED_NAME_MARKETPLACE_ID)
  private String marketplaceId;

  public static final String SERIALIZED_NAME_SHIPMENT_SERVICE_LEVEL_CATEGORY = "ShipmentServiceLevelCategory";
  @SerializedName(SERIALIZED_NAME_SHIPMENT_SERVICE_LEVEL_CATEGORY)
  private String shipmentServiceLevelCategory;

  public static final String SERIALIZED_NAME_EASY_SHIP_SHIPMENT_STATUS = "EasyShipShipmentStatus";
  @SerializedName(SERIALIZED_NAME_EASY_SHIP_SHIPMENT_STATUS)
  private String easyShipShipmentStatus;

  public static final String SERIALIZED_NAME_CBA_DISPLAYABLE_SHIPPING_LABEL = "CbaDisplayableShippingLabel";
  @SerializedName(SERIALIZED_NAME_CBA_DISPLAYABLE_SHIPPING_LABEL)
  private String cbaDisplayableShippingLabel;

  /**
   * The type of the order.
   */
  @JsonAdapter(OrderTypeEnum.Adapter.class)
  public enum OrderTypeEnum {
    STANDARDORDER("StandardOrder"),
    
    LONGLEADTIMEORDER("LongLeadTimeOrder"),
    
    PREORDER("Preorder"),
    
    BACKORDER("BackOrder"),
    
    SOURCINGONDEMANDORDER("SourcingOnDemandOrder");

    private String value;

    OrderTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OrderTypeEnum fromValue(String value) {
      for (OrderTypeEnum b : OrderTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<OrderTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OrderTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OrderTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return OrderTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ORDER_TYPE = "OrderType";
  @SerializedName(SERIALIZED_NAME_ORDER_TYPE)
  private OrderTypeEnum orderType;

  public static final String SERIALIZED_NAME_EARLIEST_SHIP_DATE = "EarliestShipDate";
  @SerializedName(SERIALIZED_NAME_EARLIEST_SHIP_DATE)
  private String earliestShipDate;

  public static final String SERIALIZED_NAME_LATEST_SHIP_DATE = "LatestShipDate";
  @SerializedName(SERIALIZED_NAME_LATEST_SHIP_DATE)
  private String latestShipDate;

  public static final String SERIALIZED_NAME_EARLIEST_DELIVERY_DATE = "EarliestDeliveryDate";
  @SerializedName(SERIALIZED_NAME_EARLIEST_DELIVERY_DATE)
  private String earliestDeliveryDate;

  public static final String SERIALIZED_NAME_LATEST_DELIVERY_DATE = "LatestDeliveryDate";
  @SerializedName(SERIALIZED_NAME_LATEST_DELIVERY_DATE)
  private String latestDeliveryDate;

  public static final String SERIALIZED_NAME_IS_BUSINESS_ORDER = "IsBusinessOrder";
  @SerializedName(SERIALIZED_NAME_IS_BUSINESS_ORDER)
  private Boolean isBusinessOrder;

  public static final String SERIALIZED_NAME_IS_PRIME = "IsPrime";
  @SerializedName(SERIALIZED_NAME_IS_PRIME)
  private Boolean isPrime;

  public static final String SERIALIZED_NAME_IS_PREMIUM_ORDER = "IsPremiumOrder";
  @SerializedName(SERIALIZED_NAME_IS_PREMIUM_ORDER)
  private Boolean isPremiumOrder;

  public static final String SERIALIZED_NAME_IS_GLOBAL_EXPRESS_ENABLED = "IsGlobalExpressEnabled";
  @SerializedName(SERIALIZED_NAME_IS_GLOBAL_EXPRESS_ENABLED)
  private Boolean isGlobalExpressEnabled;

  public static final String SERIALIZED_NAME_REPLACED_ORDER_ID = "ReplacedOrderId";
  @SerializedName(SERIALIZED_NAME_REPLACED_ORDER_ID)
  private String replacedOrderId;

  public static final String SERIALIZED_NAME_IS_REPLACEMENT_ORDER = "IsReplacementOrder";
  @SerializedName(SERIALIZED_NAME_IS_REPLACEMENT_ORDER)
  private Boolean isReplacementOrder;

  public static final String SERIALIZED_NAME_PROMISE_RESPONSE_DUE_DATE = "PromiseResponseDueDate";
  @SerializedName(SERIALIZED_NAME_PROMISE_RESPONSE_DUE_DATE)
  private String promiseResponseDueDate;

  public static final String SERIALIZED_NAME_IS_ESTIMATED_SHIP_DATE_SET = "IsEstimatedShipDateSet";
  @SerializedName(SERIALIZED_NAME_IS_ESTIMATED_SHIP_DATE_SET)
  private Boolean isEstimatedShipDateSet;

  public static final String SERIALIZED_NAME_IS_SOLD_BY_A_B = "IsSoldByAB";
  @SerializedName(SERIALIZED_NAME_IS_SOLD_BY_A_B)
  private Boolean isSoldByAB;

  public static final String SERIALIZED_NAME_DEFAULT_SHIP_FROM_LOCATION_ADDRESS = "DefaultShipFromLocationAddress";
  @SerializedName(SERIALIZED_NAME_DEFAULT_SHIP_FROM_LOCATION_ADDRESS)
  private Address defaultShipFromLocationAddress;

  public static final String SERIALIZED_NAME_FULFILLMENT_INSTRUCTION = "FulfillmentInstruction";
  @SerializedName(SERIALIZED_NAME_FULFILLMENT_INSTRUCTION)
  private FulfillmentInstruction fulfillmentInstruction;

  public static final String SERIALIZED_NAME_IS_I_S_P_U = "IsISPU";
  @SerializedName(SERIALIZED_NAME_IS_I_S_P_U)
  private Boolean isISPU;

  public static final String SERIALIZED_NAME_MARKETPLACE_TAX_INFO = "MarketplaceTaxInfo";
  @SerializedName(SERIALIZED_NAME_MARKETPLACE_TAX_INFO)
  private MarketplaceTaxInfo marketplaceTaxInfo;

  public static final String SERIALIZED_NAME_SELLER_DISPLAY_NAME = "SellerDisplayName";
  @SerializedName(SERIALIZED_NAME_SELLER_DISPLAY_NAME)
  private String sellerDisplayName;


  public Order amazonOrderId(String amazonOrderId) {
    
    this.amazonOrderId = amazonOrderId;
    return this;
  }

   /**
   * An Amazon-defined order identifier, in 3-7-7 format.
   * @return amazonOrderId
  **/
  @ApiModelProperty(required = true, value = "An Amazon-defined order identifier, in 3-7-7 format.")

  public String getAmazonOrderId() {
    return amazonOrderId;
  }


  public void setAmazonOrderId(String amazonOrderId) {
    this.amazonOrderId = amazonOrderId;
  }


  public Order sellerOrderId(String sellerOrderId) {
    
    this.sellerOrderId = sellerOrderId;
    return this;
  }

   /**
   * A seller-defined order identifier.
   * @return sellerOrderId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A seller-defined order identifier.")

  public String getSellerOrderId() {
    return sellerOrderId;
  }


  public void setSellerOrderId(String sellerOrderId) {
    this.sellerOrderId = sellerOrderId;
  }


  public Order purchaseDate(String purchaseDate) {
    
    this.purchaseDate = purchaseDate;
    return this;
  }

   /**
   * The date when the order was created.
   * @return purchaseDate
  **/
  @ApiModelProperty(required = true, value = "The date when the order was created.")

  public String getPurchaseDate() {
    return purchaseDate;
  }


  public void setPurchaseDate(String purchaseDate) {
    this.purchaseDate = purchaseDate;
  }


  public Order lastUpdateDate(String lastUpdateDate) {
    
    this.lastUpdateDate = lastUpdateDate;
    return this;
  }

   /**
   * The date when the order was last updated.  Note: LastUpdateDate is returned with an incorrect date for orders that were last updated before 2009-04-01.
   * @return lastUpdateDate
  **/
  @ApiModelProperty(required = true, value = "The date when the order was last updated.  Note: LastUpdateDate is returned with an incorrect date for orders that were last updated before 2009-04-01.")

  public String getLastUpdateDate() {
    return lastUpdateDate;
  }


  public void setLastUpdateDate(String lastUpdateDate) {
    this.lastUpdateDate = lastUpdateDate;
  }


  public Order orderStatus(OrderStatusEnum orderStatus) {
    
    this.orderStatus = orderStatus;
    return this;
  }

   /**
   * The current order status.
   * @return orderStatus
  **/
  @ApiModelProperty(required = true, value = "The current order status.")

  public OrderStatusEnum getOrderStatus() {
    return orderStatus;
  }


  public void setOrderStatus(OrderStatusEnum orderStatus) {
    this.orderStatus = orderStatus;
  }


  public Order fulfillmentChannel(FulfillmentChannelEnum fulfillmentChannel) {
    
    this.fulfillmentChannel = fulfillmentChannel;
    return this;
  }

   /**
   * Whether the order was fulfilled by Amazon (AFN) or by the seller (MFN).
   * @return fulfillmentChannel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the order was fulfilled by Amazon (AFN) or by the seller (MFN).")

  public FulfillmentChannelEnum getFulfillmentChannel() {
    return fulfillmentChannel;
  }


  public void setFulfillmentChannel(FulfillmentChannelEnum fulfillmentChannel) {
    this.fulfillmentChannel = fulfillmentChannel;
  }


  public Order salesChannel(String salesChannel) {
    
    this.salesChannel = salesChannel;
    return this;
  }

   /**
   * The sales channel of the first item in the order.
   * @return salesChannel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The sales channel of the first item in the order.")

  public String getSalesChannel() {
    return salesChannel;
  }


  public void setSalesChannel(String salesChannel) {
    this.salesChannel = salesChannel;
  }


  public Order orderChannel(String orderChannel) {
    
    this.orderChannel = orderChannel;
    return this;
  }

   /**
   * The order channel of the first item in the order.
   * @return orderChannel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The order channel of the first item in the order.")

  public String getOrderChannel() {
    return orderChannel;
  }


  public void setOrderChannel(String orderChannel) {
    this.orderChannel = orderChannel;
  }


  public Order shipServiceLevel(String shipServiceLevel) {
    
    this.shipServiceLevel = shipServiceLevel;
    return this;
  }

   /**
   * The shipment service level of the order.
   * @return shipServiceLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The shipment service level of the order.")

  public String getShipServiceLevel() {
    return shipServiceLevel;
  }


  public void setShipServiceLevel(String shipServiceLevel) {
    this.shipServiceLevel = shipServiceLevel;
  }


  public Order orderTotal(Money orderTotal) {
    
    this.orderTotal = orderTotal;
    return this;
  }

   /**
   * Get orderTotal
   * @return orderTotal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Money getOrderTotal() {
    return orderTotal;
  }


  public void setOrderTotal(Money orderTotal) {
    this.orderTotal = orderTotal;
  }


  public Order numberOfItemsShipped(Integer numberOfItemsShipped) {
    
    this.numberOfItemsShipped = numberOfItemsShipped;
    return this;
  }

   /**
   * The number of items shipped.
   * @return numberOfItemsShipped
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of items shipped.")

  public Integer getNumberOfItemsShipped() {
    return numberOfItemsShipped;
  }


  public void setNumberOfItemsShipped(Integer numberOfItemsShipped) {
    this.numberOfItemsShipped = numberOfItemsShipped;
  }


  public Order numberOfItemsUnshipped(Integer numberOfItemsUnshipped) {
    
    this.numberOfItemsUnshipped = numberOfItemsUnshipped;
    return this;
  }

   /**
   * The number of items unshipped.
   * @return numberOfItemsUnshipped
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of items unshipped.")

  public Integer getNumberOfItemsUnshipped() {
    return numberOfItemsUnshipped;
  }


  public void setNumberOfItemsUnshipped(Integer numberOfItemsUnshipped) {
    this.numberOfItemsUnshipped = numberOfItemsUnshipped;
  }


  public Order paymentExecutionDetail(List<PaymentExecutionDetailItem> paymentExecutionDetail) {
    
    this.paymentExecutionDetail = paymentExecutionDetail;
    return this;
  }

  public Order addPaymentExecutionDetailItem(PaymentExecutionDetailItem paymentExecutionDetailItem) {
    if (this.paymentExecutionDetail == null) {
      this.paymentExecutionDetail = new ArrayList<>();
    }
    this.paymentExecutionDetail.add(paymentExecutionDetailItem);
    return this;
  }

   /**
   * A list of payment execution detail items.
   * @return paymentExecutionDetail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of payment execution detail items.")

  public List<PaymentExecutionDetailItem> getPaymentExecutionDetail() {
    return paymentExecutionDetail;
  }


  public void setPaymentExecutionDetail(List<PaymentExecutionDetailItem> paymentExecutionDetail) {
    this.paymentExecutionDetail = paymentExecutionDetail;
  }


  public Order paymentMethod(PaymentMethodEnum paymentMethod) {
    
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * The payment method for the order. This property is limited to Cash On Delivery (COD) and Convenience Store (CVS) payment methods. Unless you need the specific COD payment information provided by the PaymentExecutionDetailItem object, we recommend using the PaymentMethodDetails property to get payment method information.
   * @return paymentMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The payment method for the order. This property is limited to Cash On Delivery (COD) and Convenience Store (CVS) payment methods. Unless you need the specific COD payment information provided by the PaymentExecutionDetailItem object, we recommend using the PaymentMethodDetails property to get payment method information.")

  public PaymentMethodEnum getPaymentMethod() {
    return paymentMethod;
  }


  public void setPaymentMethod(PaymentMethodEnum paymentMethod) {
    this.paymentMethod = paymentMethod;
  }


  public Order paymentMethodDetails(List<String> paymentMethodDetails) {
    
    this.paymentMethodDetails = paymentMethodDetails;
    return this;
  }

  public Order addPaymentMethodDetailsItem(String paymentMethodDetailsItem) {
    if (this.paymentMethodDetails == null) {
      this.paymentMethodDetails = new ArrayList<>();
    }
    this.paymentMethodDetails.add(paymentMethodDetailsItem);
    return this;
  }

   /**
   * A list of payment method detail items.
   * @return paymentMethodDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of payment method detail items.")

  public List<String> getPaymentMethodDetails() {
    return paymentMethodDetails;
  }


  public void setPaymentMethodDetails(List<String> paymentMethodDetails) {
    this.paymentMethodDetails = paymentMethodDetails;
  }


  public Order marketplaceId(String marketplaceId) {
    
    this.marketplaceId = marketplaceId;
    return this;
  }

   /**
   * The identifier for the marketplace where the order was placed.
   * @return marketplaceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The identifier for the marketplace where the order was placed.")

  public String getMarketplaceId() {
    return marketplaceId;
  }


  public void setMarketplaceId(String marketplaceId) {
    this.marketplaceId = marketplaceId;
  }


  public Order shipmentServiceLevelCategory(String shipmentServiceLevelCategory) {
    
    this.shipmentServiceLevelCategory = shipmentServiceLevelCategory;
    return this;
  }

   /**
   * The shipment service level category of the order.  Possible values: Expedited, FreeEconomy, NextDay, SameDay, SecondDay, Scheduled, Standard.
   * @return shipmentServiceLevelCategory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The shipment service level category of the order.  Possible values: Expedited, FreeEconomy, NextDay, SameDay, SecondDay, Scheduled, Standard.")

  public String getShipmentServiceLevelCategory() {
    return shipmentServiceLevelCategory;
  }


  public void setShipmentServiceLevelCategory(String shipmentServiceLevelCategory) {
    this.shipmentServiceLevelCategory = shipmentServiceLevelCategory;
  }


  public Order easyShipShipmentStatus(String easyShipShipmentStatus) {
    
    this.easyShipShipmentStatus = easyShipShipmentStatus;
    return this;
  }

   /**
   * The status of the Amazon Easy Ship order. This property is included only for Amazon Easy Ship orders.  Possible values: PendingPickUp, LabelCanceled, PickedUp, OutForDelivery, Damaged, Delivered, RejectedByBuyer, Undeliverable, ReturnedToSeller, ReturningToSeller.
   * @return easyShipShipmentStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The status of the Amazon Easy Ship order. This property is included only for Amazon Easy Ship orders.  Possible values: PendingPickUp, LabelCanceled, PickedUp, OutForDelivery, Damaged, Delivered, RejectedByBuyer, Undeliverable, ReturnedToSeller, ReturningToSeller.")

  public String getEasyShipShipmentStatus() {
    return easyShipShipmentStatus;
  }


  public void setEasyShipShipmentStatus(String easyShipShipmentStatus) {
    this.easyShipShipmentStatus = easyShipShipmentStatus;
  }


  public Order cbaDisplayableShippingLabel(String cbaDisplayableShippingLabel) {
    
    this.cbaDisplayableShippingLabel = cbaDisplayableShippingLabel;
    return this;
  }

   /**
   * Custom ship label for Checkout by Amazon (CBA).
   * @return cbaDisplayableShippingLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Custom ship label for Checkout by Amazon (CBA).")

  public String getCbaDisplayableShippingLabel() {
    return cbaDisplayableShippingLabel;
  }


  public void setCbaDisplayableShippingLabel(String cbaDisplayableShippingLabel) {
    this.cbaDisplayableShippingLabel = cbaDisplayableShippingLabel;
  }


  public Order orderType(OrderTypeEnum orderType) {
    
    this.orderType = orderType;
    return this;
  }

   /**
   * The type of the order.
   * @return orderType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type of the order.")

  public OrderTypeEnum getOrderType() {
    return orderType;
  }


  public void setOrderType(OrderTypeEnum orderType) {
    this.orderType = orderType;
  }


  public Order earliestShipDate(String earliestShipDate) {
    
    this.earliestShipDate = earliestShipDate;
    return this;
  }

   /**
   * The start of the time period within which you have committed to ship the order. In ISO 8601 date time format. Returned only for seller-fulfilled orders.  Note: EarliestShipDate might not be returned for orders placed before February 1, 2013.
   * @return earliestShipDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The start of the time period within which you have committed to ship the order. In ISO 8601 date time format. Returned only for seller-fulfilled orders.  Note: EarliestShipDate might not be returned for orders placed before February 1, 2013.")

  public String getEarliestShipDate() {
    return earliestShipDate;
  }


  public void setEarliestShipDate(String earliestShipDate) {
    this.earliestShipDate = earliestShipDate;
  }


  public Order latestShipDate(String latestShipDate) {
    
    this.latestShipDate = latestShipDate;
    return this;
  }

   /**
   * The end of the time period within which you have committed to ship the order. In ISO 8601 date time format. Returned only for seller-fulfilled orders.  Note: LatestShipDate might not be returned for orders placed before February 1, 2013.
   * @return latestShipDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The end of the time period within which you have committed to ship the order. In ISO 8601 date time format. Returned only for seller-fulfilled orders.  Note: LatestShipDate might not be returned for orders placed before February 1, 2013.")

  public String getLatestShipDate() {
    return latestShipDate;
  }


  public void setLatestShipDate(String latestShipDate) {
    this.latestShipDate = latestShipDate;
  }


  public Order earliestDeliveryDate(String earliestDeliveryDate) {
    
    this.earliestDeliveryDate = earliestDeliveryDate;
    return this;
  }

   /**
   * The start of the time period within which you have committed to fulfill the order. In ISO 8601 date time format. Returned only for seller-fulfilled orders.
   * @return earliestDeliveryDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The start of the time period within which you have committed to fulfill the order. In ISO 8601 date time format. Returned only for seller-fulfilled orders.")

  public String getEarliestDeliveryDate() {
    return earliestDeliveryDate;
  }


  public void setEarliestDeliveryDate(String earliestDeliveryDate) {
    this.earliestDeliveryDate = earliestDeliveryDate;
  }


  public Order latestDeliveryDate(String latestDeliveryDate) {
    
    this.latestDeliveryDate = latestDeliveryDate;
    return this;
  }

   /**
   * The end of the time period within which you have committed to fulfill the order. In ISO 8601 date time format. Returned only for seller-fulfilled orders that do not have a PendingAvailability, Pending, or Canceled status.
   * @return latestDeliveryDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The end of the time period within which you have committed to fulfill the order. In ISO 8601 date time format. Returned only for seller-fulfilled orders that do not have a PendingAvailability, Pending, or Canceled status.")

  public String getLatestDeliveryDate() {
    return latestDeliveryDate;
  }


  public void setLatestDeliveryDate(String latestDeliveryDate) {
    this.latestDeliveryDate = latestDeliveryDate;
  }


  public Order isBusinessOrder(Boolean isBusinessOrder) {
    
    this.isBusinessOrder = isBusinessOrder;
    return this;
  }

   /**
   * When true, the order is an Amazon Business order. An Amazon Business order is an order where the buyer is a Verified Business Buyer.
   * @return isBusinessOrder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When true, the order is an Amazon Business order. An Amazon Business order is an order where the buyer is a Verified Business Buyer.")

  public Boolean getIsBusinessOrder() {
    return isBusinessOrder;
  }


  public void setIsBusinessOrder(Boolean isBusinessOrder) {
    this.isBusinessOrder = isBusinessOrder;
  }


  public Order isPrime(Boolean isPrime) {
    
    this.isPrime = isPrime;
    return this;
  }

   /**
   * When true, the order is a seller-fulfilled Amazon Prime order.
   * @return isPrime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When true, the order is a seller-fulfilled Amazon Prime order.")

  public Boolean getIsPrime() {
    return isPrime;
  }


  public void setIsPrime(Boolean isPrime) {
    this.isPrime = isPrime;
  }


  public Order isPremiumOrder(Boolean isPremiumOrder) {
    
    this.isPremiumOrder = isPremiumOrder;
    return this;
  }

   /**
   * When true, the order has a Premium Shipping Service Level Agreement. For more information about Premium Shipping orders, see \&quot;Premium Shipping Options\&quot; in the Seller Central Help for your marketplace.
   * @return isPremiumOrder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When true, the order has a Premium Shipping Service Level Agreement. For more information about Premium Shipping orders, see \"Premium Shipping Options\" in the Seller Central Help for your marketplace.")

  public Boolean getIsPremiumOrder() {
    return isPremiumOrder;
  }


  public void setIsPremiumOrder(Boolean isPremiumOrder) {
    this.isPremiumOrder = isPremiumOrder;
  }


  public Order isGlobalExpressEnabled(Boolean isGlobalExpressEnabled) {
    
    this.isGlobalExpressEnabled = isGlobalExpressEnabled;
    return this;
  }

   /**
   * When true, the order is a GlobalExpress order.
   * @return isGlobalExpressEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When true, the order is a GlobalExpress order.")

  public Boolean getIsGlobalExpressEnabled() {
    return isGlobalExpressEnabled;
  }


  public void setIsGlobalExpressEnabled(Boolean isGlobalExpressEnabled) {
    this.isGlobalExpressEnabled = isGlobalExpressEnabled;
  }


  public Order replacedOrderId(String replacedOrderId) {
    
    this.replacedOrderId = replacedOrderId;
    return this;
  }

   /**
   * The order ID value for the order that is being replaced. Returned only if IsReplacementOrder &#x3D; true.
   * @return replacedOrderId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The order ID value for the order that is being replaced. Returned only if IsReplacementOrder = true.")

  public String getReplacedOrderId() {
    return replacedOrderId;
  }


  public void setReplacedOrderId(String replacedOrderId) {
    this.replacedOrderId = replacedOrderId;
  }


  public Order isReplacementOrder(Boolean isReplacementOrder) {
    
    this.isReplacementOrder = isReplacementOrder;
    return this;
  }

   /**
   * When true, this is a replacement order.
   * @return isReplacementOrder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When true, this is a replacement order.")

  public Boolean getIsReplacementOrder() {
    return isReplacementOrder;
  }


  public void setIsReplacementOrder(Boolean isReplacementOrder) {
    this.isReplacementOrder = isReplacementOrder;
  }


  public Order promiseResponseDueDate(String promiseResponseDueDate) {
    
    this.promiseResponseDueDate = promiseResponseDueDate;
    return this;
  }

   /**
   * Indicates the date by which the seller must respond to the buyer with an estimated ship date. Returned only for Sourcing on Demand orders.
   * @return promiseResponseDueDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates the date by which the seller must respond to the buyer with an estimated ship date. Returned only for Sourcing on Demand orders.")

  public String getPromiseResponseDueDate() {
    return promiseResponseDueDate;
  }


  public void setPromiseResponseDueDate(String promiseResponseDueDate) {
    this.promiseResponseDueDate = promiseResponseDueDate;
  }


  public Order isEstimatedShipDateSet(Boolean isEstimatedShipDateSet) {
    
    this.isEstimatedShipDateSet = isEstimatedShipDateSet;
    return this;
  }

   /**
   * When true, the estimated ship date is set for the order. Returned only for Sourcing on Demand orders.
   * @return isEstimatedShipDateSet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When true, the estimated ship date is set for the order. Returned only for Sourcing on Demand orders.")

  public Boolean getIsEstimatedShipDateSet() {
    return isEstimatedShipDateSet;
  }


  public void setIsEstimatedShipDateSet(Boolean isEstimatedShipDateSet) {
    this.isEstimatedShipDateSet = isEstimatedShipDateSet;
  }


  public Order isSoldByAB(Boolean isSoldByAB) {
    
    this.isSoldByAB = isSoldByAB;
    return this;
  }

   /**
   * When true, the item within this order was bought and re-sold by Amazon Business EU SARL (ABEU). By buying and instantly re-selling your items, ABEU becomes the seller of record, making your inventory available for sale to customers who would not otherwise purchase from a third-party seller.
   * @return isSoldByAB
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When true, the item within this order was bought and re-sold by Amazon Business EU SARL (ABEU). By buying and instantly re-selling your items, ABEU becomes the seller of record, making your inventory available for sale to customers who would not otherwise purchase from a third-party seller.")

  public Boolean getIsSoldByAB() {
    return isSoldByAB;
  }


  public void setIsSoldByAB(Boolean isSoldByAB) {
    this.isSoldByAB = isSoldByAB;
  }


  public Order defaultShipFromLocationAddress(Address defaultShipFromLocationAddress) {
    
    this.defaultShipFromLocationAddress = defaultShipFromLocationAddress;
    return this;
  }

   /**
   * Get defaultShipFromLocationAddress
   * @return defaultShipFromLocationAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Address getDefaultShipFromLocationAddress() {
    return defaultShipFromLocationAddress;
  }


  public void setDefaultShipFromLocationAddress(Address defaultShipFromLocationAddress) {
    this.defaultShipFromLocationAddress = defaultShipFromLocationAddress;
  }


  public Order fulfillmentInstruction(FulfillmentInstruction fulfillmentInstruction) {
    
    this.fulfillmentInstruction = fulfillmentInstruction;
    return this;
  }

   /**
   * Get fulfillmentInstruction
   * @return fulfillmentInstruction
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public FulfillmentInstruction getFulfillmentInstruction() {
    return fulfillmentInstruction;
  }


  public void setFulfillmentInstruction(FulfillmentInstruction fulfillmentInstruction) {
    this.fulfillmentInstruction = fulfillmentInstruction;
  }


  public Order isISPU(Boolean isISPU) {
    
    this.isISPU = isISPU;
    return this;
  }

   /**
   * When true, this order is marked to be picked up from a store rather than delivered.
   * @return isISPU
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When true, this order is marked to be picked up from a store rather than delivered.")

  public Boolean getIsISPU() {
    return isISPU;
  }


  public void setIsISPU(Boolean isISPU) {
    this.isISPU = isISPU;
  }


  public Order marketplaceTaxInfo(MarketplaceTaxInfo marketplaceTaxInfo) {
    
    this.marketplaceTaxInfo = marketplaceTaxInfo;
    return this;
  }

   /**
   * Get marketplaceTaxInfo
   * @return marketplaceTaxInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MarketplaceTaxInfo getMarketplaceTaxInfo() {
    return marketplaceTaxInfo;
  }


  public void setMarketplaceTaxInfo(MarketplaceTaxInfo marketplaceTaxInfo) {
    this.marketplaceTaxInfo = marketplaceTaxInfo;
  }


  public Order sellerDisplayName(String sellerDisplayName) {
    
    this.sellerDisplayName = sellerDisplayName;
    return this;
  }

   /**
   * The seller’s friendly name registered in the marketplace.
   * @return sellerDisplayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The seller’s friendly name registered in the marketplace.")

  public String getSellerDisplayName() {
    return sellerDisplayName;
  }


  public void setSellerDisplayName(String sellerDisplayName) {
    this.sellerDisplayName = sellerDisplayName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Order order = (Order) o;
    return Objects.equals(this.amazonOrderId, order.amazonOrderId) &&
        Objects.equals(this.sellerOrderId, order.sellerOrderId) &&
        Objects.equals(this.purchaseDate, order.purchaseDate) &&
        Objects.equals(this.lastUpdateDate, order.lastUpdateDate) &&
        Objects.equals(this.orderStatus, order.orderStatus) &&
        Objects.equals(this.fulfillmentChannel, order.fulfillmentChannel) &&
        Objects.equals(this.salesChannel, order.salesChannel) &&
        Objects.equals(this.orderChannel, order.orderChannel) &&
        Objects.equals(this.shipServiceLevel, order.shipServiceLevel) &&
        Objects.equals(this.orderTotal, order.orderTotal) &&
        Objects.equals(this.numberOfItemsShipped, order.numberOfItemsShipped) &&
        Objects.equals(this.numberOfItemsUnshipped, order.numberOfItemsUnshipped) &&
        Objects.equals(this.paymentExecutionDetail, order.paymentExecutionDetail) &&
        Objects.equals(this.paymentMethod, order.paymentMethod) &&
        Objects.equals(this.paymentMethodDetails, order.paymentMethodDetails) &&
        Objects.equals(this.marketplaceId, order.marketplaceId) &&
        Objects.equals(this.shipmentServiceLevelCategory, order.shipmentServiceLevelCategory) &&
        Objects.equals(this.easyShipShipmentStatus, order.easyShipShipmentStatus) &&
        Objects.equals(this.cbaDisplayableShippingLabel, order.cbaDisplayableShippingLabel) &&
        Objects.equals(this.orderType, order.orderType) &&
        Objects.equals(this.earliestShipDate, order.earliestShipDate) &&
        Objects.equals(this.latestShipDate, order.latestShipDate) &&
        Objects.equals(this.earliestDeliveryDate, order.earliestDeliveryDate) &&
        Objects.equals(this.latestDeliveryDate, order.latestDeliveryDate) &&
        Objects.equals(this.isBusinessOrder, order.isBusinessOrder) &&
        Objects.equals(this.isPrime, order.isPrime) &&
        Objects.equals(this.isPremiumOrder, order.isPremiumOrder) &&
        Objects.equals(this.isGlobalExpressEnabled, order.isGlobalExpressEnabled) &&
        Objects.equals(this.replacedOrderId, order.replacedOrderId) &&
        Objects.equals(this.isReplacementOrder, order.isReplacementOrder) &&
        Objects.equals(this.promiseResponseDueDate, order.promiseResponseDueDate) &&
        Objects.equals(this.isEstimatedShipDateSet, order.isEstimatedShipDateSet) &&
        Objects.equals(this.isSoldByAB, order.isSoldByAB) &&
        Objects.equals(this.defaultShipFromLocationAddress, order.defaultShipFromLocationAddress) &&
        Objects.equals(this.fulfillmentInstruction, order.fulfillmentInstruction) &&
        Objects.equals(this.isISPU, order.isISPU) &&
        Objects.equals(this.marketplaceTaxInfo, order.marketplaceTaxInfo) &&
        Objects.equals(this.sellerDisplayName, order.sellerDisplayName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amazonOrderId, sellerOrderId, purchaseDate, lastUpdateDate, orderStatus, fulfillmentChannel, salesChannel, orderChannel, shipServiceLevel, orderTotal, numberOfItemsShipped, numberOfItemsUnshipped, paymentExecutionDetail, paymentMethod, paymentMethodDetails, marketplaceId, shipmentServiceLevelCategory, easyShipShipmentStatus, cbaDisplayableShippingLabel, orderType, earliestShipDate, latestShipDate, earliestDeliveryDate, latestDeliveryDate, isBusinessOrder, isPrime, isPremiumOrder, isGlobalExpressEnabled, replacedOrderId, isReplacementOrder, promiseResponseDueDate, isEstimatedShipDateSet, isSoldByAB, defaultShipFromLocationAddress, fulfillmentInstruction, isISPU, marketplaceTaxInfo, sellerDisplayName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Order {\n");
    sb.append("    amazonOrderId: ").append(toIndentedString(amazonOrderId)).append("\n");
    sb.append("    sellerOrderId: ").append(toIndentedString(sellerOrderId)).append("\n");
    sb.append("    purchaseDate: ").append(toIndentedString(purchaseDate)).append("\n");
    sb.append("    lastUpdateDate: ").append(toIndentedString(lastUpdateDate)).append("\n");
    sb.append("    orderStatus: ").append(toIndentedString(orderStatus)).append("\n");
    sb.append("    fulfillmentChannel: ").append(toIndentedString(fulfillmentChannel)).append("\n");
    sb.append("    salesChannel: ").append(toIndentedString(salesChannel)).append("\n");
    sb.append("    orderChannel: ").append(toIndentedString(orderChannel)).append("\n");
    sb.append("    shipServiceLevel: ").append(toIndentedString(shipServiceLevel)).append("\n");
    sb.append("    orderTotal: ").append(toIndentedString(orderTotal)).append("\n");
    sb.append("    numberOfItemsShipped: ").append(toIndentedString(numberOfItemsShipped)).append("\n");
    sb.append("    numberOfItemsUnshipped: ").append(toIndentedString(numberOfItemsUnshipped)).append("\n");
    sb.append("    paymentExecutionDetail: ").append(toIndentedString(paymentExecutionDetail)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    paymentMethodDetails: ").append(toIndentedString(paymentMethodDetails)).append("\n");
    sb.append("    marketplaceId: ").append(toIndentedString(marketplaceId)).append("\n");
    sb.append("    shipmentServiceLevelCategory: ").append(toIndentedString(shipmentServiceLevelCategory)).append("\n");
    sb.append("    easyShipShipmentStatus: ").append(toIndentedString(easyShipShipmentStatus)).append("\n");
    sb.append("    cbaDisplayableShippingLabel: ").append(toIndentedString(cbaDisplayableShippingLabel)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    earliestShipDate: ").append(toIndentedString(earliestShipDate)).append("\n");
    sb.append("    latestShipDate: ").append(toIndentedString(latestShipDate)).append("\n");
    sb.append("    earliestDeliveryDate: ").append(toIndentedString(earliestDeliveryDate)).append("\n");
    sb.append("    latestDeliveryDate: ").append(toIndentedString(latestDeliveryDate)).append("\n");
    sb.append("    isBusinessOrder: ").append(toIndentedString(isBusinessOrder)).append("\n");
    sb.append("    isPrime: ").append(toIndentedString(isPrime)).append("\n");
    sb.append("    isPremiumOrder: ").append(toIndentedString(isPremiumOrder)).append("\n");
    sb.append("    isGlobalExpressEnabled: ").append(toIndentedString(isGlobalExpressEnabled)).append("\n");
    sb.append("    replacedOrderId: ").append(toIndentedString(replacedOrderId)).append("\n");
    sb.append("    isReplacementOrder: ").append(toIndentedString(isReplacementOrder)).append("\n");
    sb.append("    promiseResponseDueDate: ").append(toIndentedString(promiseResponseDueDate)).append("\n");
    sb.append("    isEstimatedShipDateSet: ").append(toIndentedString(isEstimatedShipDateSet)).append("\n");
    sb.append("    isSoldByAB: ").append(toIndentedString(isSoldByAB)).append("\n");
    sb.append("    defaultShipFromLocationAddress: ").append(toIndentedString(defaultShipFromLocationAddress)).append("\n");
    sb.append("    fulfillmentInstruction: ").append(toIndentedString(fulfillmentInstruction)).append("\n");
    sb.append("    isISPU: ").append(toIndentedString(isISPU)).append("\n");
    sb.append("    marketplaceTaxInfo: ").append(toIndentedString(marketplaceTaxInfo)).append("\n");
    sb.append("    sellerDisplayName: ").append(toIndentedString(sellerDisplayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

