/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.metas.camel.externalsystems.amazon.api.model.orders;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.metas.camel.externalsystems.amazon.api.model.orders.BuyerCustomizedInfoDetail;
import de.metas.camel.externalsystems.amazon.api.model.orders.Money;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A single order item&#39;s buyer information.
 */
@ApiModel(description = "A single order item's buyer information.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-19T18:02:29.893848+02:00[Europe/Berlin]")
public class OrderItemBuyerInfo {
  public static final String SERIALIZED_NAME_ORDER_ITEM_ID = "OrderItemId";
  @SerializedName(SERIALIZED_NAME_ORDER_ITEM_ID)
  private String orderItemId;

  public static final String SERIALIZED_NAME_BUYER_CUSTOMIZED_INFO = "BuyerCustomizedInfo";
  @SerializedName(SERIALIZED_NAME_BUYER_CUSTOMIZED_INFO)
  private BuyerCustomizedInfoDetail buyerCustomizedInfo;

  public static final String SERIALIZED_NAME_GIFT_WRAP_PRICE = "GiftWrapPrice";
  @SerializedName(SERIALIZED_NAME_GIFT_WRAP_PRICE)
  private Money giftWrapPrice;

  public static final String SERIALIZED_NAME_GIFT_WRAP_TAX = "GiftWrapTax";
  @SerializedName(SERIALIZED_NAME_GIFT_WRAP_TAX)
  private Money giftWrapTax;

  public static final String SERIALIZED_NAME_GIFT_MESSAGE_TEXT = "GiftMessageText";
  @SerializedName(SERIALIZED_NAME_GIFT_MESSAGE_TEXT)
  private String giftMessageText;

  public static final String SERIALIZED_NAME_GIFT_WRAP_LEVEL = "GiftWrapLevel";
  @SerializedName(SERIALIZED_NAME_GIFT_WRAP_LEVEL)
  private String giftWrapLevel;


  public OrderItemBuyerInfo orderItemId(String orderItemId) {
    
    this.orderItemId = orderItemId;
    return this;
  }

   /**
   * An Amazon-defined order item identifier.
   * @return orderItemId
  **/
  @ApiModelProperty(required = true, value = "An Amazon-defined order item identifier.")

  public String getOrderItemId() {
    return orderItemId;
  }


  public void setOrderItemId(String orderItemId) {
    this.orderItemId = orderItemId;
  }


  public OrderItemBuyerInfo buyerCustomizedInfo(BuyerCustomizedInfoDetail buyerCustomizedInfo) {
    
    this.buyerCustomizedInfo = buyerCustomizedInfo;
    return this;
  }

   /**
   * Get buyerCustomizedInfo
   * @return buyerCustomizedInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BuyerCustomizedInfoDetail getBuyerCustomizedInfo() {
    return buyerCustomizedInfo;
  }


  public void setBuyerCustomizedInfo(BuyerCustomizedInfoDetail buyerCustomizedInfo) {
    this.buyerCustomizedInfo = buyerCustomizedInfo;
  }


  public OrderItemBuyerInfo giftWrapPrice(Money giftWrapPrice) {
    
    this.giftWrapPrice = giftWrapPrice;
    return this;
  }

   /**
   * Get giftWrapPrice
   * @return giftWrapPrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Money getGiftWrapPrice() {
    return giftWrapPrice;
  }


  public void setGiftWrapPrice(Money giftWrapPrice) {
    this.giftWrapPrice = giftWrapPrice;
  }


  public OrderItemBuyerInfo giftWrapTax(Money giftWrapTax) {
    
    this.giftWrapTax = giftWrapTax;
    return this;
  }

   /**
   * Get giftWrapTax
   * @return giftWrapTax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Money getGiftWrapTax() {
    return giftWrapTax;
  }


  public void setGiftWrapTax(Money giftWrapTax) {
    this.giftWrapTax = giftWrapTax;
  }


  public OrderItemBuyerInfo giftMessageText(String giftMessageText) {
    
    this.giftMessageText = giftMessageText;
    return this;
  }

   /**
   * A gift message provided by the buyer.
   * @return giftMessageText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A gift message provided by the buyer.")

  public String getGiftMessageText() {
    return giftMessageText;
  }


  public void setGiftMessageText(String giftMessageText) {
    this.giftMessageText = giftMessageText;
  }


  public OrderItemBuyerInfo giftWrapLevel(String giftWrapLevel) {
    
    this.giftWrapLevel = giftWrapLevel;
    return this;
  }

   /**
   * The gift wrap level specified by the buyer.
   * @return giftWrapLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The gift wrap level specified by the buyer.")

  public String getGiftWrapLevel() {
    return giftWrapLevel;
  }


  public void setGiftWrapLevel(String giftWrapLevel) {
    this.giftWrapLevel = giftWrapLevel;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderItemBuyerInfo orderItemBuyerInfo = (OrderItemBuyerInfo) o;
    return Objects.equals(this.orderItemId, orderItemBuyerInfo.orderItemId) &&
        Objects.equals(this.buyerCustomizedInfo, orderItemBuyerInfo.buyerCustomizedInfo) &&
        Objects.equals(this.giftWrapPrice, orderItemBuyerInfo.giftWrapPrice) &&
        Objects.equals(this.giftWrapTax, orderItemBuyerInfo.giftWrapTax) &&
        Objects.equals(this.giftMessageText, orderItemBuyerInfo.giftMessageText) &&
        Objects.equals(this.giftWrapLevel, orderItemBuyerInfo.giftWrapLevel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderItemId, buyerCustomizedInfo, giftWrapPrice, giftWrapTax, giftMessageText, giftWrapLevel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderItemBuyerInfo {\n");
    sb.append("    orderItemId: ").append(toIndentedString(orderItemId)).append("\n");
    sb.append("    buyerCustomizedInfo: ").append(toIndentedString(buyerCustomizedInfo)).append("\n");
    sb.append("    giftWrapPrice: ").append(toIndentedString(giftWrapPrice)).append("\n");
    sb.append("    giftWrapTax: ").append(toIndentedString(giftWrapTax)).append("\n");
    sb.append("    giftMessageText: ").append(toIndentedString(giftMessageText)).append("\n");
    sb.append("    giftWrapLevel: ").append(toIndentedString(giftWrapLevel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

