/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.metas.camel.externalsystems.amazon.api.model.orders;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.metas.camel.externalsystems.amazon.api.model.orders.Money;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The number of Amazon Points offered with the purchase of an item, and their monetary value.
 */
@ApiModel(description = "The number of Amazon Points offered with the purchase of an item, and their monetary value.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-19T18:02:29.893848+02:00[Europe/Berlin]")
public class PointsGrantedDetail {
  public static final String SERIALIZED_NAME_POINTS_NUMBER = "PointsNumber";
  @SerializedName(SERIALIZED_NAME_POINTS_NUMBER)
  private Integer pointsNumber;

  public static final String SERIALIZED_NAME_POINTS_MONETARY_VALUE = "PointsMonetaryValue";
  @SerializedName(SERIALIZED_NAME_POINTS_MONETARY_VALUE)
  private Money pointsMonetaryValue;


  public PointsGrantedDetail pointsNumber(Integer pointsNumber) {
    
    this.pointsNumber = pointsNumber;
    return this;
  }

   /**
   * The number of Amazon Points granted with the purchase of an item.
   * @return pointsNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of Amazon Points granted with the purchase of an item.")

  public Integer getPointsNumber() {
    return pointsNumber;
  }


  public void setPointsNumber(Integer pointsNumber) {
    this.pointsNumber = pointsNumber;
  }


  public PointsGrantedDetail pointsMonetaryValue(Money pointsMonetaryValue) {
    
    this.pointsMonetaryValue = pointsMonetaryValue;
    return this;
  }

   /**
   * Get pointsMonetaryValue
   * @return pointsMonetaryValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Money getPointsMonetaryValue() {
    return pointsMonetaryValue;
  }


  public void setPointsMonetaryValue(Money pointsMonetaryValue) {
    this.pointsMonetaryValue = pointsMonetaryValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PointsGrantedDetail pointsGrantedDetail = (PointsGrantedDetail) o;
    return Objects.equals(this.pointsNumber, pointsGrantedDetail.pointsNumber) &&
        Objects.equals(this.pointsMonetaryValue, pointsGrantedDetail.pointsMonetaryValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pointsNumber, pointsMonetaryValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PointsGrantedDetail {\n");
    sb.append("    pointsNumber: ").append(toIndentedString(pointsNumber)).append("\n");
    sb.append("    pointsMonetaryValue: ").append(toIndentedString(pointsMonetaryValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

