/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.metas.camel.externalsystems.amazon.api.model.orders;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Information about withheld taxes.
 */
@ApiModel(description = "Information about withheld taxes.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-19T18:02:29.893848+02:00[Europe/Berlin]")
public class TaxCollection {
  /**
   * The tax collection model applied to the item.
   */
  @JsonAdapter(ModelEnum.Adapter.class)
  public enum ModelEnum {
    MARKETPLACEFACILITATOR("MarketplaceFacilitator");

    private String value;

    ModelEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ModelEnum fromValue(String value) {
      for (ModelEnum b : ModelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ModelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ModelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ModelEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ModelEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_MODEL = "Model";
  @SerializedName(SERIALIZED_NAME_MODEL)
  private ModelEnum model;

  /**
   * The party responsible for withholding the taxes and remitting them to the taxing authority.
   */
  @JsonAdapter(ResponsiblePartyEnum.Adapter.class)
  public enum ResponsiblePartyEnum {
    AMAZON_SERVICES_INC_("Amazon Services, Inc.");

    private String value;

    ResponsiblePartyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ResponsiblePartyEnum fromValue(String value) {
      for (ResponsiblePartyEnum b : ResponsiblePartyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ResponsiblePartyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ResponsiblePartyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ResponsiblePartyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ResponsiblePartyEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_RESPONSIBLE_PARTY = "ResponsibleParty";
  @SerializedName(SERIALIZED_NAME_RESPONSIBLE_PARTY)
  private ResponsiblePartyEnum responsibleParty;


  public TaxCollection model(ModelEnum model) {
    
    this.model = model;
    return this;
  }

   /**
   * The tax collection model applied to the item.
   * @return model
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The tax collection model applied to the item.")

  public ModelEnum getModel() {
    return model;
  }


  public void setModel(ModelEnum model) {
    this.model = model;
  }


  public TaxCollection responsibleParty(ResponsiblePartyEnum responsibleParty) {
    
    this.responsibleParty = responsibleParty;
    return this;
  }

   /**
   * The party responsible for withholding the taxes and remitting them to the taxing authority.
   * @return responsibleParty
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The party responsible for withholding the taxes and remitting them to the taxing authority.")

  public ResponsiblePartyEnum getResponsibleParty() {
    return responsibleParty;
  }


  public void setResponsibleParty(ResponsiblePartyEnum responsibleParty) {
    this.responsibleParty = responsibleParty;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaxCollection taxCollection = (TaxCollection) o;
    return Objects.equals(this.model, taxCollection.model) &&
        Objects.equals(this.responsibleParty, taxCollection.responsibleParty);
  }

  @Override
  public int hashCode() {
    return Objects.hash(model, responsibleParty);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaxCollection {\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    responsibleParty: ").append(toIndentedString(responsibleParty)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

